name: UpCloud Infrastructure Deployment

on:
  push:
    branches: [ main ]
    paths:
      - '**.tf'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_LOG: INFO
  TF_VAR_network_family: "IPv4"
  TF_VAR_network_dhcp: true
  TF_VAR_zone: "fi-hel2"
  TF_VAR_private_network_name: "production-network"
  TF_VAR_uks_node_count: 24

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Configure Environment Variables
      run: |
        echo "TF_VAR_admin_username=${{ secrets.DB_ADMIN_USERNAME }}" >> $GITHUB_ENV
        echo "TF_VAR_admin_password=${{ secrets.DB_ADMIN_PASSWORD }}" >> $GITHUB_ENV
        echo "TF_VAR_tls_certificate_id=${{ secrets.TLS_CERTIFICATE_ID }}" >> $GITHUB_ENV
        echo "TF_VAR_upcloud_username=${{ secrets.UPCLOUD_USERNAME }}" >> $GITHUB_ENV
        echo "TF_VAR_upcloud_password=${{ secrets.UPCLOUD_PASSWORD }}" >> $GITHUB_ENV

    - name: Terraform Init
      env:
        TF_VAR_upcloud_username: ${{ secrets.UPCLOUD_USERNAME }}
        TF_VAR_upcloud_password: ${{ secrets.UPCLOUD_PASSWORD }}
      run: terraform init

    - name: Terraform Destroy
      env:
        TF_VAR_upcloud_username: ${{ secrets.UPCLOUD_USERNAME }}
        TF_VAR_upcloud_password: ${{ secrets.UPCLOUD_PASSWORD }}
      run: terraform destroy
